rel_a_fazer = {
    # 'Jardim Elba':'SB-11',
    # 'Fazenda da Juta III': 'HSB-07',
    # 'Brás de Abreu': 'HAD-04',
    # 'Maria Cursi': 'SM-03',
    # 'Jardim Umuarama II': 'CL-12',
    # 'Tanque': 'SB-06',
    # 'Jardim Filhos da Terra': 'JT-02',
    # 'Kaei Kawahira': 'SM-29',
    # 'Parque Boa Esperança': 'SM-33',
    # 'Jardim Hebrom': 'JT-05',
    # 'Jardim Jangadeiro': 'MB-33',
    # 'Taquaritiba': 'JA-09',
    # 'Vila Ayrosa': 'JT-08',
    # 'Iguaçu': 'SB-08',
    # 'Vila Praia': 'CL-21',
    # 'Ushikichi Kamiya': 'JT-22',
    # 'Jardim Marciano': 'CL-26',
    # 'Barrocada III': 'JT-21',
    # 'Palácio Monroe': 'HPJ-07',
    
    # 'Jardim das Maravilhas I': 'CT-03',
    # 'Jardim Primavera II': 'HSB-03',
    # 'Vila Flávia':'SM-16',
    # 'Alameda das Roseiras':'JT-18',
    # 'Gráficos': 'CT-06',
    # 'Jardim Maraba':'IQ-17',
    # 'Chacara Bandeirante':'MB-53',
    
    # 'Vila Bela II': 'HSM-11',
    # 'Cidade Ipava II': 'MB-60',
    # 'Córrego Pintadinho': 'HIQ-04',
    # 'Taquari': 'HIQ-09',
    # 'Parque São José IV': 'CS-09',
    # 'Camarazal': 'BT-12',
    # 'Jardim São Jorge': 'AD-13',
    # 'Jardim Macedônia': 'CL-29',
    # 'Francisco Munhoz Filho': 'IQ-15',
    'Piscinão': 'SM-25',
    # 'Fazendinha': 'LA-07',
    # 'Murillo Machado': 'SM-23',
    # 'Souza Ramos': 'CT-07',
    # 'Jardim Santa Terezinha IV': 'IQ-03',
    # 'Jardim Santa Terezinha III': 'IQ-02',
    # 'Ministro Correia De Castro': 'FO-16',
    # 'Nossa Senhora Assunção': 'BT-17',
    # 'Recanto Verde I': 'SM-01',
    # 'Morumbizinho': 'SM-32',
    # 'Jardim Filhos Da Terra': 'JT-02',
    # 'Jardim Martini': 'AD-22',
    # 'Jardim São Carlos': 'HAD-21',
    # 'Santa Etelvina III': 'CT-08',
    # PROBLEMA - Não está pronto: 'Engordador': 'JT-12',
    # 'Jardim Solange': 'SM-31',
    # 'Guaicuri II': 'HAD-25',
    # 'Jardim Rebouças': 'CL-18',
    # 'Recanto': 'SM-26',
    # 'Rio Claro II': 'SM-21',
    # 'Jardim Das Laranjeiras': 'SM-02',
    # 'Sebastião Afonso': 'HAD-02',
    # 'Jardim Alfredo': 'MB-30',
    # 'Jardim Ibirapuera': 'MB-02',
    # 'Vila Clara - Ubs': 'JA-04',
    # 'Tantas Palavras': 'IQ-14',
    # 'São Vicente': 'HIQ-01',
#    'Mata Virgem - Água Santa': 'AD-11'
    
}